### ISSUE TITLE
Value of hidden input is not set when the form is sent pressing enter key

### ISSUE THREAD

**Issue by jayala** [kartik-v/yii2-money#12] opened 2015-05-29 18:37 UTC
If you press enter a value and press enter the form is sent, but the value is not saved. This is caused because the value is saved with the blur event. To solve this I made a modification to the keyDown event, by firing blurEvent when enter key is pressed.

**Comment by tx350z** [comment] 2016-06-05 10:27
Confirmed this is still broken in v1.2.1.

**Comment by tx350z** [comment] 2017-05-16 12:36
This is STILL a problem with Firefox. It works fine with IE. Any update on a fix? My site will be moving to production in the near future and this is a major concern since it causes loss of data.

Thank you!

kartik/yii-money version 1.2.1
Firefox version 53.0.2 (32-bit)
OS: Windows 8.1with all patches

**Comment by kartik-v** [comment] 2017-05-23 10:59
Resolved via [updates & enhancements to release v1.2.2](https://github.com/kartik-v/yii2-money/commit/6c18c47b6561e52ecd4cff9d2e0c3a0e974c236f). Duplicate to #24, #17, #4.

**Closed by kartik-v** 2017-05-23 10:59 UTC
Labels: bug, duplicate
