### ISSUE TITLE
Problems with prefix like ''

### ISSUE THREAD

**Issue by lukBarros** [kartik-v/yii2-money#32] opened 2017-12-06 20:27 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-money.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/money).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-money version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/money)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-money without other plugins.

**Comment by ricpelo** [comment] 2018-01-29 13:44
Seems to be a duplicate of #28.

**Comment by kartik-v** [comment] 2018-01-30 13:03
The new [yii2-number extension](http://demos.krajee.com/number) has been released and is now a replacement for the yii2-money extension. Recommend to head over to use that extension.

**Closed** 2018-01-30 13:03 UTC
